# Site settings
author: Itzel Ortiz
title: Cheli's Blog
header-img: img/home-bg.png
email: itzelortiz72@gmail.com
copyright_name: Itzel Ortiz
description: > # this means to ignore newlines until "baseurl:"
  For Small Snippets of my Life
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ItzelOrtiz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
